import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class AppLanguage {
  final Locale locale;
  final String name;
  final String nativeName;
  const AppLanguage(this.locale, this.name, this.nativeName);
}

const supportedLanguages = [
  AppLanguage(Locale('en'), 'English', 'English'),
  AppLanguage(Locale('hi'), 'Hindi', 'हिन्दी'),
  AppLanguage(Locale('te'), 'Telugu', 'తెలుగు'),
  AppLanguage(Locale('ta'), 'Tamil', 'தமிழ்'),
  AppLanguage(Locale('mr'), 'Marathi', 'मराठी'),
  AppLanguage(Locale('gu'), 'Gujarati', 'ગુજરાતી'),
  AppLanguage(Locale('bn'), 'Bengali', 'বাংলা'),
  AppLanguage(Locale('kn'), 'Kannada', 'ಕನ್ನಡ'),
  AppLanguage(Locale('as'), 'Assamese', 'অসমীয়া'),
];

class LocalizationService extends ChangeNotifier {
  static const _key = 'harvestflow.language';
  Locale _locale = const Locale('en');
  Locale get locale => _locale;

  Future<void> load() async {
    final p = await SharedPreferences.getInstance();
    final code = p.getString(_key);
    if (code != null && supportedLanguages.any((x) => x.locale.languageCode == code)) {
      _locale = Locale(code);
    }
    notifyListeners();
  }

  Future<void> setLanguage(Locale locale) async {
    _locale = locale;
    notifyListeners();
    final p = await SharedPreferences.getInstance();
    await p.setString(_key, locale.languageCode);
  }

  String t(String key) {
    return _strings[_locale.languageCode]?[key] ??
        _strings['en']?[key] ??
        key;
  }
}

const Map<String, Map<String, String>> _strings = {
  'en': {
    // App & Brand
    'app_title': 'HarvestFlow',
    'app_tagline': 'Harvesting Planning, Purchase, Sales & Logistics',
    'role_notice': 'Your role is assigned by your account — the backend returns it from your credentials.',

    // Auth & Login
    'login': 'Log In',
    'logging_in': 'Logging in...',
    'username': 'Username',
    'password': 'Password',
    'language': 'Language',
    'select_language': 'Select Language',
    'forgot': 'Forgot password?',
    'forgot_password': 'Forgot password?',
    'register': 'Register User',
    'register_user': 'Register User',
    'enter_username_password': 'Enter both username and password.',
    'session_expired': 'Your session has expired. Please log in again.',
    'server_error': 'Could not reach the server. Check your connection and try again.',

    // Registration
    'register_title': 'Register User',
    'step_account': 'Account',
    'step_mobile_otp': 'Mobile OTP',
    'step_aadhaar_otp': 'Aadhaar OTP',
    'step_role': 'Role',
    'step_address': 'Address',
    'step_documents': 'Documents',
    'step_review': 'Review',
    'full_name': 'Full name',
    'email': 'Email',
    'mobile_number': 'Mobile number',
    'enter_valid_mobile': 'Enter valid 10-digit mobile',
    'aadhaar_number': 'Aadhaar number',
    'enter_valid_aadhaar': 'Enter 12 digits',
    'send_otp': 'Send OTP',
    'send_aadhaar_otp': 'Send Aadhaar OTP',
    'verify_otp': 'Verify OTP',
    'otp_verified': 'Verified ✓',
    'enter_6_digit_otp': '6-digit OTP',
    'select_role': 'Select Role',
    'address_line': 'Address',
    'village_city': 'Village / City',
    'district': 'District',
    'state': 'State',
    'pincode': 'Pincode',
    'enter_valid_pincode': 'Enter 6-digit pincode',
    'upload_khet_receipt': 'Khet / Farm land receipt',
    'upload_signature': 'Signature',
    'upload_photo': 'Photo',
    'not_uploaded': 'Not uploaded',
    'uploaded': 'Uploaded',
    'upload_all_docs': 'Upload all three required documents.',
    'upload_and_continue': 'Upload & Continue',
    'submit_registration': 'Submit Registration',
    'registration_complete': 'Registration complete',
    'go_to_login': 'Go to Login',
    'required': 'Required',
    'min_8_chars': 'Minimum 8 characters',
    'password_complexity': 'Use upper, lower, digit and special character',

    // Roles
    'role_farmer': 'Farmer',
    'role_fpo': 'FPO',
    'role_consumer': 'Consumer',
    'role_bulk_buyer': 'Bulk Buyer',
    'role_admin': 'Admin',
    'role_plot_selection': 'Plot Selection',
    'role_planning': 'Planning Team',
    'role_godown': 'Godown Officer',
    'role_supervisor': 'Supervisor',
    'role_purchase_account': 'Purchase Account',
    'role_pickup_person': 'Pickup Person',
    'role_transport_person': 'Transport Coordinator',
    'role_labor_coordinator': 'Labor Coordinator',
    'role_eicher_driver': 'Eicher Truck Driver',

    // Dashboard & Actions
    'dashboard': 'Dashboard',
    'pending_cases': 'Pending Queue',
    'no_pending_cases': 'No pending cases for your role right now.',
    'active_trips': 'Active Trips',
    'notifications': 'Notifications',
    'admin_tools': 'Admin Tools',
    'browse_cases': 'Browse All Cases',
    'logout': 'Log Out',
    'refresh': 'Refresh',
    'retry': 'Retry',
    'cancel': 'Cancel',
    'save': 'Save',
    'submit': 'Submit',
    'continue_btn': 'Continue',
    'back': 'Back',
    'accept': 'Accept',

    // Logistics & Payment
    'acceptOrder': 'Accept Order',
    'payment': 'Payment',
    'payNow': 'Pay Now',
    'cash': 'Cash',
    'digital': 'Digital Payment',
    'deliveryOtp': 'Delivery OTP',
    'generateOtp': 'Generate Delivery OTP',
    'confirmPickup': 'Confirm Pickup',
    'reachBuyer': 'Reached Buyer',
    'completeDelivery': 'Complete Delivery',
    'receipt': 'Receipt',
    'bankDetails': 'Farmer Bank Details',
    'accountHolder': 'Account holder name',
    'accountNumber': 'Bank account number',
    'ifsc': 'IFSC code',
    'bankName': 'Bank name'
  },
  'hi': {
    // App & Brand
    'app_title': 'हार्वेस्ट-फ्लो',
    'app_tagline': 'फसल कटाई योजना, खरीद, बिक्री एवं लॉजिस्टिक्स',
    'role_notice': 'आपकी भूमिका आपके खाते से निर्धारित होती है — बैकएंड आपके क्रेडेंशियल्स से इसकी पुष्टि करता है।',

    // Auth & Login
    'login': 'लॉग इन',
    'logging_in': 'लॉग इन हो रहा है...',
    'username': 'उपयोगकर्ता नाम',
    'password': 'पासवर्ड',
    'language': 'भाषा',
    'select_language': 'भाषा चुनें',
    'forgot': 'पासवर्ड भूल गए?',
    'forgot_password': 'पासवर्ड भूल गए?',
    'register': 'उपयोगकर्ता पंजीकरण',
    'register_user': 'उपयोगकर्ता पंजीकरण',
    'enter_username_password': 'कृपया उपयोगकर्ता नाम और पासवर्ड दोनों दर्ज करें।',
    'session_expired': 'आपका सत्र समाप्त हो गया है। कृपया पुनः लॉग इन करें।',
    'server_error': 'सर्वर से संपर्क नहीं हो सका। कृपया अपना कनेक्शन जांचें।',

    // Registration
    'register_title': 'उपयोगकर्ता पंजीकरण',
    'step_account': 'खाता',
    'step_mobile_otp': 'मोबाइल OTP',
    'step_aadhaar_otp': 'आधार OTP',
    'step_role': 'भूमिका',
    'step_address': 'पता',
    'step_documents': 'दस्तावेज़',
    'step_review': 'समीक्षा',
    'full_name': 'पूरा नाम',
    'email': 'ईमेल',
    'mobile_number': 'मोबाइल नंबर',
    'enter_valid_mobile': '10 अंकों का मान्य मोबाइल नंबर दर्ज करें',
    'aadhaar_number': 'आधार संख्या',
    'enter_valid_aadhaar': '12 अंकों का आधार नंबर दर्ज करें',
    'send_otp': 'OTP भेजें',
    'send_aadhaar_otp': 'आधार OTP भेजें',
    'verify_otp': 'OTP सत्यापित करें',
    'otp_verified': 'सत्यापित ✓',
    'enter_6_digit_otp': '6-अंकीय OTP दर्ज करें',
    'select_role': 'भूमिका चुनें',
    'address_line': 'पता',
    'village_city': 'गाँव / शहर',
    'district': 'जिला',
    'state': 'राज्य',
    'pincode': 'पिनकोड',
    'enter_valid_pincode': '6 अंकों का पिनकोड दर्ज करें',
    'upload_khet_receipt': 'खेत / भूमि रसीद',
    'upload_signature': 'हस्ताक्षर',
    'upload_photo': 'फोटो',
    'not_uploaded': 'अपलोड नहीं हुआ',
    'uploaded': 'अपलोड हो गया',
    'upload_all_docs': 'तीनों आवश्यक दस्तावेज़ अपलोड करें।',
    'upload_and_continue': 'अपलोड करें और आगे बढ़ें',
    'submit_registration': 'पंजीकरण जमा करें',
    'registration_complete': 'पंजीकरण पूर्ण हुआ',
    'go_to_login': 'लॉग इन पर जाएं',
    'required': 'आवश्यक',
    'min_8_chars': 'कम से कम 8 अक्षर',
    'password_complexity': 'बड़ा अक्षर, छोटा अक्षर, संख्या और विशेष वर्ण का प्रयोग करें',

    // Roles
    'role_farmer': 'किसान',
    'role_fpo': 'एफपीओ',
    'role_consumer': 'उपभोक्ता',
    'role_bulk_buyer': 'थोक खरीदार',
    'role_admin': 'व्यवस्थापक',
    'role_plot_selection': 'प्लॉट चयनकर्ता',
    'role_planning': 'योजना टीम',
    'role_godown': 'गोदाम अधिकारी',
    'role_supervisor': 'सुपरवाइजर',
    'role_purchase_account': 'खरीद खाता टीम',
    'role_pickup_person': 'पिकअप व्यक्ति',
    'role_transport_person': 'परिवहन समन्वयक',
    'role_labor_coordinator': 'श्रम समन्वयक',
    'role_eicher_driver': 'आयशर ट्रक चालक',

    // Dashboard & Actions
    'dashboard': 'डैशबोर्ड',
    'pending_cases': 'लंबित कार्य सूची',
    'no_pending_cases': 'वर्तमान में आपकी भूमिका के लिए कोई कार्य लंबित नहीं है।',
    'active_trips': 'सक्रिय यात्राएं',
    'notifications': 'सूचनाएं',
    'admin_tools': 'व्यवस्थापक उपकरण',
    'browse_cases': 'सभी मामले देखें',
    'logout': 'लॉग आउट',
    'refresh': 'रिफ्रेश करें',
    'retry': 'पुनः प्रयास करें',
    'cancel': 'रद्द करें',
    'save': 'सहेजें',
    'submit': 'जमा करें',
    'continue_btn': 'आगे बढ़ें',
    'back': 'पीछे',
    'accept': 'स्वीकार करें',

    // Logistics & Payment
    'acceptOrder': 'ऑर्डर स्वीकार करें',
    'payment': 'भुगतान',
    'payNow': 'अभी भुगतान करें',
    'cash': 'नकद',
    'digital': 'डिजिटल भुगतान',
    'deliveryOtp': 'डिलीवरी OTP',
    'generateOtp': 'डिलीवरी OTP जनरेट करें',
    'confirmPickup': 'पिकअप की पुष्टि करें',
    'reachBuyer': 'खरीदार तक पहुँच गए',
    'completeDelivery': 'डिलीवरी पूरी करें',
    'receipt': 'रसीद',
    'bankDetails': 'किसान बैंक विवरण',
    'accountHolder': 'खाता धारक का नाम',
    'accountNumber': 'बैंक खाता संख्या',
    'ifsc': 'IFSC कोड',
    'bankName': 'बैंक का नाम'
  },
  'te': {
    // App & Brand
    'app_title': 'హార్వెస్ట్‌ఫ్లో',
    'app_tagline': 'పంట కోత ప్రణాళిక, కొనుగోలు, అమ్మకాలు & లాజిస్టిక్స్',
    'role_notice': 'మీ పాత్ర మీ ఖాతా ద్వారా కేటాయించబడుతుంది — బ్యాకెండ్ మీ ఆధారాల నుండి దీనిని గుర్తిస్తుంది.',

    // Auth & Login
    'login': 'లాగిన్',
    'logging_in': 'లాగిన్ అవుతోంది...',
    'username': 'వినియోగదారు పేరు',
    'password': 'పాస్‌వర్డ్',
    'language': 'భాష',
    'select_language': 'భాషను ఎంచుకోండి',
    'forgot': 'పాస్‌వర్డ్ మర్చిపోయారా?',
    'forgot_password': 'పాస్‌వర్డ్ మర్చిపోయారా?',
    'register': 'వినియోగదారు నమోదు',
    'register_user': 'వినియోగదారు నమోదు',
    'enter_username_password': 'వినియోగదారు పేరు మరియు పాస్‌వర్డ్ రెండింటినీ నమోదు చేయండి.',
    'session_expired': 'మీ సెషన్ గడువు ముగిసింది. దయచేసి మళ్లీ లాగిన్ అవ్వండి.',
    'server_error': 'సర్వర్‌ను చేరుకోలేకపోయాము. దయచేసి మీ ఇంటర్నెట్ కనెక్షన్‌ని తనిఖీ చేయండి.',

    // Registration
    'register_title': 'వినియోగదారు నమోదు',
    'step_account': 'ఖాతా',
    'step_mobile_otp': 'మొబైల్ OTP',
    'step_aadhaar_otp': 'ఆధార్ OTP',
    'step_role': 'పాత్ర',
    'step_address': 'చిరునామా',
    'step_documents': 'పత్రాలు',
    'step_review': 'సమీక్ష',
    'full_name': 'పూర్తి పేరు',
    'email': 'ఇమెయిల్',
    'mobile_number': 'మొబైల్ నంబర్',
    'enter_valid_mobile': 'చెల్లుబాటు అయ్యే 10 అంకెల మొబైల్ నంబర్‌ను నమోదు చేయండి',
    'aadhaar_number': 'ఆధార్ సంఖ్య',
    'enter_valid_aadhaar': '12 అంకెల ఆధార్ సంఖ్యను నమోదు చేయండి',
    'send_otp': 'OTP పంపండి',
    'send_aadhaar_otp': 'ఆధార్ OTP పంపండి',
    'verify_otp': 'OTP ధృవీకరించండి',
    'otp_verified': 'ధృవీకరించబడింది ✓',
    'enter_6_digit_otp': '6 అంకెల OTP ని నమోదు చేయండి',
    'select_role': 'పాత్రను ఎంచుకోండి',
    'address_line': 'చిరునామా',
    'village_city': 'గ్రామం / నగరం',
    'district': 'జిల్లా',
    'state': 'రాష్ట్రం',
    'pincode': 'పిన్‌కోడ్',
    'enter_valid_pincode': '6 అంకెల పిన్‌కోడ్‌ను నమోదు చేయండి',
    'upload_khet_receipt': 'భూమి రసీదు',
    'upload_signature': 'సంతకం',
    'upload_photo': 'ఫోటో',
    'not_uploaded': 'అప్‌లోడ్ చేయలేదు',
    'uploaded': 'అప్‌లోడ్ చేయబడింది',
    'upload_all_docs': 'అవసరమైన మూడు పత్రాలను అప్‌లోడ్ చేయండి.',
    'upload_and_continue': 'అప్‌లోడ్ చేసి కొనసాగించండి',
    'submit_registration': 'రిజిస్ట్రేషన్ సమర్పించండి',
    'registration_complete': 'రిజిస్ట్రేషన్ పూర్తయింది',
    'go_to_login': 'లాగిన్‌కు వెళ్లండి',
    'required': 'తప్పనిసరి',
    'min_8_chars': 'కనీసం 8 అక్షరాలు ఉండాలి',
    'password_complexity': 'పెద్ద అక్షరం, చిన్న అక్షరం, సంఖ్య మరియు ప్రత్యేక చిహ్నాన్ని ఉపయోగించండి',

    // Roles
    'role_farmer': 'రైతు',
    'role_fpo': 'ఎఫ్.పి.ఒ',
    'role_consumer': 'వినియోగదారుడు',
    'role_bulk_buyer': 'బల్క్ కొనుగోలుదారు',
    'role_admin': 'నిర్వాహకుడు',
    'role_plot_selection': 'ప్లాట్ ఎంపిక',
    'role_planning': 'ప్లానింగ్ బృందం',
    'role_godown': 'గోదాము అధికారి',
    'role_supervisor': 'సూపర్‌వైజర్',
    'role_purchase_account': 'కొనుగోలు ఖాతా బృందం',
    'role_pickup_person': 'పికప్ వ్యక్తి',
    'role_transport_person': 'రవాణా సమన్వయకర్త',
    'role_labor_coordinator': 'కార్మిక సమన్వయకర్త',
    'role_eicher_driver': 'ఐషర్ ట్రక్ డ్రైవర్',

    // Dashboard & Actions
    'dashboard': 'డ్యాష్‌బోర్డ్',
    'pending_cases': 'పెండింగ్ జాబితా',
    'no_pending_cases': 'ప్రస్తుతం మీ పాత్రకు పెండింగ్ కేసులు లేవు.',
    'active_trips': 'క్రియాశీల పర్యటనలు',
    'notifications': 'నోటిఫికేషన్లు',
    'admin_tools': 'అడ్మిన్ సాధనాలు',
    'browse_cases': 'అన్ని కేసులను బ్రౌజ్ చేయండి',
    'logout': 'లాగ్ అవుట్',
    'refresh': 'రిఫ్రెష్ చేయండి',
    'retry': 'మళ్లీ ప్రయత్నించండి',
    'cancel': 'రద్దు చేయండి',
    'save': 'సేవ్ చేయండి',
    'submit': 'సమర్పించండి',
    'continue_btn': 'కొనసాగించండి',
    'back': 'వెనుకకు',
    'accept': 'అంగీకరించండి',

    // Logistics & Payment
    'acceptOrder': 'ఆర్డర్‌ను అంగీకరించండి',
    'payment': 'చెల్లింపు',
    'payNow': 'ఇప్పుడే చెల్లించండి',
    'cash': 'నగదు',
    'digital': 'డిజిటల్ చెల్లింపు',
    'deliveryOtp': 'డెలివరీ OTP',
    'generateOtp': 'డెలివరీ OTP రూపొందించండి',
    'confirmPickup': 'పికప్ నిర్ధారించండి',
    'reachBuyer': 'కొనుగోలుదారుని చేరుకున్నాం',
    'completeDelivery': 'డెలివరీ పూర్తి చేయండి',
    'receipt': 'రసీదు',
    'bankDetails': 'రైతు బ్యాంక్ వివరాలు',
    'accountHolder': 'ఖాతాదారు పేరు',
    'accountNumber': 'బ్యాంక్ ఖాతా సంఖ్య',
    'ifsc': 'IFSC కోడ్',
    'bankName': 'బ్యాంక్ పేరు'
  },
  'ta': {
    'login': 'உள்நுழைக',
    'username': 'பயனர் பெயர்',
    'password': 'கடவுச்சொல்',
    'language': 'மொழி',
    'forgot': 'கடவுச்சொல்லை மறந்துவிட்டீர்களா?',
    'register': 'பயனர் பதிவு',
    'acceptOrder': 'ஆர்டரை ஏற்கவும்',
    'payment': 'பணம் செலுத்துதல்',
    'payNow': 'இப்போது செலுத்தவும்',
    'cash': 'ரொக்கம்',
    'digital': 'டிஜிட்டல் பணம்',
    'deliveryOtp': 'டெலிவரி OTP',
    'generateOtp': 'டெலிவரி OTP உருவாக்கவும்',
    'confirmPickup': 'பிக்கப்பை உறுதிசெய்க',
    'reachBuyer': 'வாங்குபவரை அடைந்தது',
    'completeDelivery': 'டெலிவரியை முடிக்கவும்',
    'receipt': 'ரசீது',
    'bankDetails': 'விவசாயி வங்கி விவரங்கள்',
    'accountHolder': 'கணக்கு வைத்திருப்பவர் பெயர்',
    'accountNumber': 'வங்கி கணக்கு எண்',
    'ifsc': 'IFSC குறியீடு',
    'bankName': 'வங்கி பெயர்'
  },
  'mr': {
    'login': 'लॉग इन',
    'username': 'वापरकर्ता नाव',
    'password': 'पासवर्ड',
    'language': 'भाषा',
    'forgot': 'पासवर्ड विसरलात?',
    'register': 'वापरकर्ता नोंदणी',
    'acceptOrder': 'ऑर्डर स्वीकारा',
    'payment': 'पेमेंट',
    'payNow': 'आता भरा',
    'cash': 'रोख',
    'digital': 'डिजिटल पेमेंट',
    'deliveryOtp': 'डिलिव्हरी OTP',
    'generateOtp': 'डिलिव्हरी OTP तयार करा',
    'confirmPickup': 'पिकअपची पुष्टी करा',
    'reachBuyer': 'खरेदीदारापर्यंत पोहोचलो',
    'completeDelivery': 'डिलिव्हरी पूर्ण करा',
    'receipt': 'पावती',
    'bankDetails': 'शेतकरी बँक तपशील',
    'accountHolder': 'खातेधारकाचे नाव',
    'accountNumber': 'बँक खाते क्रमांक',
    'ifsc': 'IFSC कोड',
    'bankName': 'बँकेचे नाव'
  },
  'gu': {
    'login': 'લોગ ઇન',
    'username': 'વપરાશકર્તા નામ',
    'password': 'પાસવર્ડ',
    'language': 'ભાષા',
    'forgot': 'પાસવર્ડ ભૂલી ગયા?',
    'register': 'વપરાશકર્તા નોંધણી',
    'acceptOrder': 'ઓર્ડર સ્વીકારો',
    'payment': 'ચુકવણી',
    'payNow': 'હવે ચૂકવો',
    'cash': 'રોકડ',
    'digital': 'ડિજિટલ ચુકવણી',
    'deliveryOtp': 'ડિલિવરી OTP',
    'generateOtp': 'ડિલિવરી OTP બનાવો',
    'confirmPickup': 'પિકઅપની પુષ્ટિ કરો',
    'reachBuyer': 'ખરીદદાર સુધી પહોંચ્યા',
    'completeDelivery': 'ડિલિવરી પૂર્ણ કરો',
    'receipt': 'રસીદ',
    'bankDetails': 'ખેડૂત બેંક વિગતો',
    'accountHolder': 'ખાતા ધારકનું નામ',
    'accountNumber': 'બેંક ખાતા નંબર',
    'ifsc': 'IFSC કોડ',
    'bankName': 'બેંકનું નામ'
  },
  'as': {
    'login': 'লগ ইন',
    'username': 'ব্যৱহাৰকাৰীৰ নাম',
    'password': 'পাছৱৰ্ড',
    'language': 'ভাষা',
    'forgot': 'পাছৱৰ্ড পাহৰিছে?',
    'register': 'ব্যৱহাৰকাৰী পঞ্জীয়ন',
    'acceptOrder': 'অৰ্ডাৰ গ্ৰহণ কৰক',
    'payment': 'পেমেণ্ট',
    'payNow': 'এতিয়া পেমেণ্ট কৰক',
    'cash': 'নগদ',
    'digital': 'ডিজিটেল পেমেণ্ট',
    'deliveryOtp': 'ডেলিভাৰী OTP',
    'generateOtp': 'ডেলিভাৰী OTP সৃষ্টি কৰক',
    'confirmPickup': 'পিকআপ নিশ্চিত কৰক',
    'reachBuyer': 'ক্ৰেতাৰ ওচৰ পালোঁ',
    'completeDelivery': 'ডেলিভাৰী সম্পূৰ্ণ কৰক',
    'receipt': 'ৰচিদ',
    'bankDetails': 'কৃষকৰ বেংক বিৱৰণ',
    'accountHolder': 'একাউণ্টধাৰীৰ নাম',
    'accountNumber': 'বেংক একাউণ্ট নম্বৰ',
    'ifsc': 'IFSC ক’ড',
    'bankName': 'বেংকৰ নাম'
  },
  'bn': {
    'login': 'লগ ইন',
    'username': 'ব্যবহারকারীর নাম',
    'password': 'পাসওয়ার্ড',
    'language': 'ভাষা',
    'forgot': 'পাসওয়ার্ড ভুলে গেছেন?',
    'register': 'ব্যবহারকারী নিবন্ধন',
    'acceptOrder': 'অর্ডার গ্রহণ করুন',
    'payment': 'পেমেন্ট',
    'payNow': 'এখন পেমেন্ট করুন',
    'cash': 'নগদ',
    'digital': 'ডিজিটাল পেমেন্ট',
    'deliveryOtp': 'ডেলিভারি OTP',
    'generateOtp': 'ডেলিভারি OTP তৈরি করুন',
    'confirmPickup': 'পিকআপ নিশ্চিত করুন',
    'reachBuyer': 'ক্রেতার কাছে পৌঁছেছি',
    'completeDelivery': 'ডেলিভারি সম্পূর্ণ করুন',
    'receipt': 'রসিদ',
    'bankDetails': 'কৃষকের ব্যাংক বিবরণ',
    'accountHolder': 'অ্যাকাউন্টধারীর নাম',
    'accountNumber': 'ব্যাংক অ্যাকাউন্ট নম্বর',
    'ifsc': 'IFSC কোড',
    'bankName': 'ব্যাংকের নাম'
  },
  'kn': {
    'login': 'ಲಾಗಿನ್',
    'username': 'ಬಳಕೆದಾರ ಹೆಸರು',
    'password': 'ಪಾಸ್‌ವರ್ಡ್',
    'language': 'ಭಾಷೆ',
    'forgot': 'ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿರಾ?',
    'register': 'ಬಳಕೆದಾರ ನೋಂದಣಿ',
    'acceptOrder': 'ಆರ್ಡರ್ ಸ್ವೀಕರಿಸಿ',
    'payment': 'ಪಾವತಿ',
    'payNow': 'ಈಗ ಪಾವತಿಸಿ',
    'cash': 'ನಗದು',
    'digital': 'ಡಿಜಿಟಲ್ ಪಾವತಿ',
    'deliveryOtp': 'ಡೆಲಿವರಿ OTP',
    'generateOtp': 'ಡೆಲಿವರಿ OTP ರಚಿಸಿ',
    'confirmPickup': 'ಪಿಕಪ್ ದೃಢೀಕರಿಸಿ',
    'reachBuyer': 'ಖರೀದಿದಾರರನ್ನು ತಲುಪಿದೆ',
    'completeDelivery': 'ಡೆಲಿವರಿ ಪೂರ್ಣಗೊಳಿಸಿ',
    'receipt': 'ರಸೀದಿ',
    'bankDetails': 'ರೈತ ಬ್ಯಾಂಕ್ ವಿವರಗಳು',
    'accountHolder': 'ಖಾತೆದಾರರ ಹೆಸರು',
    'accountNumber': 'ಬ್ಯಾಂಕ್ ಖಾತೆ ಸಂಖ್ಯೆ',
    'ifsc': 'IFSC ಕೋಡ್',
    'bankName': 'ಬ್ಯಾಂಕ್ ಹೆಸರು'
  }
};
