import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class AppLanguage { final Locale locale; final String name; const AppLanguage(this.locale,this.name); }
const supportedLanguages = [AppLanguage(Locale('en'),'English'),AppLanguage(Locale('hi'),'Hindi'),AppLanguage(Locale('ta'),'Tamil'),AppLanguage(Locale('mr'),'Marathi'),AppLanguage(Locale('gu'),'Gujarati'),AppLanguage(Locale('as'),'Assamese'),AppLanguage(Locale('bn'),'Bengali'),AppLanguage(Locale('te'),'Telugu'),AppLanguage(Locale('kn'),'Kannada')];
class LocalizationService extends ChangeNotifier {
 static const _key='harvestflow.language'; Locale _locale=const Locale('en'); Locale get locale=>_locale;
 Future<void> load() async {final p=await SharedPreferences.getInstance(); final code=p.getString(_key); if(code!=null&&supportedLanguages.any((x)=>x.locale.languageCode==code)) _locale=Locale(code); notifyListeners();}
 Future<void> setLanguage(Locale locale) async { _locale=locale; notifyListeners(); final p=await SharedPreferences.getInstance(); await p.setString(_key,locale.languageCode); }
 String t(String key){return _strings[_locale.languageCode]?[key]??_strings['en']![key]??key;}
}
const Map<String,Map<String,String>> _strings={
'en':{'login':'Log In','username':'Username','password':'Password','language':'Language','forgot':'Forgot password?','register':'Register User','acceptOrder':'Accept Order','payment':'Payment','payNow':'Pay Now','cash':'Cash','digital':'Digital Payment','deliveryOtp':'Delivery OTP','generateOtp':'Generate Delivery OTP','confirmPickup':'Confirm Pickup','reachBuyer':'Reached Buyer','completeDelivery':'Complete Delivery','receipt':'Receipt','bankDetails':'Farmer Bank Details','accountHolder':'Account holder name','accountNumber':'Bank account number','ifsc':'IFSC code','bankName':'Bank name'},
'hi':{'login':'लॉग इन','username':'उपयोगकर्ता नाम','password':'पासवर्ड','language':'भाषा','forgot':'पासवर्ड भूल गए?','register':'उपयोगकर्ता पंजीकरण','acceptOrder':'ऑर्डर स्वीकार करें','payment':'भुगतान','payNow':'अभी भुगतान करें','cash':'नकद','digital':'डिजिटल भुगतान','deliveryOtp':'डिलीवरी OTP','generateOtp':'डिलीवरी OTP जनरेट करें','confirmPickup':'पिकअप की पुष्टि करें','reachBuyer':'खरीदार तक पहुँच गए','completeDelivery':'डिलीवरी पूरी करें','receipt':'रसीद','bankDetails':'किसान बैंक विवरण','accountHolder':'खाता धारक का नाम','accountNumber':'बैंक खाता संख्या','ifsc':'IFSC कोड','bankName':'बैंक का नाम'},
'ta':{'login':'உள்நுழைக','username':'பயனர் பெயர்','password':'கடவுச்சொல்','language':'மொழி','forgot':'கடவுச்சொல்லை மறந்துவிட்டீர்களா?','register':'பயனர் பதிவு','acceptOrder':'ஆர்டரை ஏற்கவும்','payment':'பணம் செலுத்துதல்','payNow':'இப்போது செலுத்தவும்','cash':'ரொக்கம்','digital':'டிஜிட்டல் பணம்','deliveryOtp':'டெலிவரி OTP','generateOtp':'டெலிவரி OTP உருவாக்கவும்','confirmPickup':'பிக்கப்பை உறுதிசெய்க','reachBuyer':'வாங்குபவரை அடைந்தது','completeDelivery':'டெலிவரியை முடிக்கவும்','receipt':'ரசீது','bankDetails':'விவசாயி வங்கி விவரங்கள்','accountHolder':'கணக்கு வைத்திருப்பவர் பெயர்','accountNumber':'வங்கி கணக்கு எண்','ifsc':'IFSC குறியீடு','bankName':'வங்கி பெயர்'},
'mr':{'login':'लॉग इन','username':'वापरकर्ता नाव','password':'पासवर्ड','language':'भाषा','forgot':'पासवर्ड विसरलात?','register':'वापरकर्ता नोंदणी','acceptOrder':'ऑर्डर स्वीकारा','payment':'पेमेंट','payNow':'आता भरा','cash':'रोख','digital':'डिजिटल पेमेंट','deliveryOtp':'डिलिव्हरी OTP','generateOtp':'डिलिव्हरी OTP तयार करा','confirmPickup':'पिकअपची पुष्टी करा','reachBuyer':'खरेदीदारापर्यंत पोहोचलो','completeDelivery':'डिलिव्हरी पूर्ण करा','receipt':'पावती','bankDetails':'शेतकरी बँक तपशील','accountHolder':'खातेधारकाचे नाव','accountNumber':'बँक खाते क्रमांक','ifsc':'IFSC कोड','bankName':'बँकेचे नाव'},
'gu':{'login':'લોગ ઇન','username':'વપરાશકર્તા નામ','password':'પાસવર્ડ','language':'ભાષા','forgot':'પાસવર્ડ ભૂલી ગયા?','register':'વપરાશકર્તા નોંધણી','acceptOrder':'ઓર્ડર સ્વીકારો','payment':'ચુકવણી','payNow':'હવે ચૂકવો','cash':'રોકડ','digital':'ડિજિટલ ચુકવણી','deliveryOtp':'ડિલિવરી OTP','generateOtp':'ડિલિવરી OTP બનાવો','confirmPickup':'પિકઅપની પુષ્ટિ કરો','reachBuyer':'ખરીદદાર સુધી પહોંચ્યા','completeDelivery':'ડિલિવરી પૂર્ણ કરો','receipt':'રસીદ','bankDetails':'ખેડૂત બેંક વિગતો','accountHolder':'ખાતા ધારકનું નામ','accountNumber':'બેંક ખાતા નંબર','ifsc':'IFSC કોડ','bankName':'બેંકનું નામ'},
'as':{'login':'লগ ইন','username':'ব্যৱহাৰকাৰীৰ নাম','password':'পাছৱৰ্ড','language':'ভাষা','forgot':'পাছৱৰ্ড পাহৰিছে?','register':'ব্যৱহাৰকাৰী পঞ্জীয়ন','acceptOrder':'অৰ্ডাৰ গ্ৰহণ কৰক','payment':'পেমেণ্ট','payNow':'এতিয়া পেমেণ্ট কৰক','cash':'নগদ','digital':'ডিজিটেল পেমেণ্ট','deliveryOtp':'ডেলিভাৰী OTP','generateOtp':'ডেলিভাৰী OTP সৃষ্টি কৰক','confirmPickup':'পিকআপ নিশ্চিত কৰক','reachBuyer':'ক্ৰেতাৰ ওচৰ পালোঁ','completeDelivery':'ডেলিভাৰী সম্পূৰ্ণ কৰক','receipt':'ৰচিদ','bankDetails':'কৃষকৰ বেংক বিৱৰণ','accountHolder':'একাউণ্টধাৰীৰ নাম','accountNumber':'বেংক একাউণ্ট নম্বৰ','ifsc':'IFSC ক’ড','bankName':'বেংকৰ নাম'},
'bn':{'login':'লগ ইন','username':'ব্যবহারকারীর নাম','password':'পাসওয়ার্ড','language':'ভাষা','forgot':'পাসওয়ার্ড ভুলে গেছেন?','register':'ব্যবহারকারী নিবন্ধন','acceptOrder':'অর্ডার গ্রহণ করুন','payment':'পেমেন্ট','payNow':'এখন পেমেন্ট করুন','cash':'নগদ','digital':'ডিজিটাল পেমেন্ট','deliveryOtp':'ডেলিভারি OTP','generateOtp':'ডেলিভারি OTP তৈরি করুন','confirmPickup':'পিকআপ নিশ্চিত করুন','reachBuyer':'ক্রেতার কাছে পৌঁছেছি','completeDelivery':'ডেলিভারি সম্পূর্ণ করুন','receipt':'রসিদ','bankDetails':'কৃষকের ব্যাংক বিবরণ','accountHolder':'অ্যাকাউন্টধারীর নাম','accountNumber':'ব্যাংক অ্যাকাউন্ট নম্বর','ifsc':'IFSC কোড','bankName':'ব্যাংকের নাম'},
'te':{'login':'లాగిన్','username':'వినియోగదారు పేరు','password':'పాస్‌వర్డ్','language':'భాష','forgot':'పాస్‌వర్డ్ మర్చిపోయారా?','register':'వినియోగదారు నమోదు','acceptOrder':'ఆర్డర్‌ను అంగీకరించండి','payment':'చెల్లింపు','payNow':'ఇప్పుడే చెల్లించండి','cash':'నగదు','digital':'డిజిటల్ చెల్లింపు','deliveryOtp':'డెలివరీ OTP','generateOtp':'డెలివరీ OTP రూపొందించండి','confirmPickup':'పికప్ నిర్ధారించండి','reachBuyer':'కొనుగోలుదారుని చేరుకున్నాం','completeDelivery':'డెలివరీ పూర్తి చేయండి','receipt':'రసీదు','bankDetails':'రైతు బ్యాంక్ వివరాలు','accountHolder':'ఖాతాదారు పేరు','accountNumber':'బ్యాంక్ ఖాతా సంఖ్య','ifsc':'IFSC కోడ్','bankName':'బ్యాంక్ పేరు'},
'kn':{'login':'ಲಾಗಿನ್','username':'ಬಳಕೆದಾರ ಹೆಸರು','password':'ಪಾಸ್‌ವರ್ಡ್','language':'ಭಾಷೆ','forgot':'ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿರಾ?','register':'ಬಳಕೆದಾರ ನೋಂದಣಿ','acceptOrder':'ಆರ್ಡರ್ ಸ್ವೀಕರಿಸಿ','payment':'ಪಾವತಿ','payNow':'ಈಗ ಪಾವತಿಸಿ','cash':'ನಗದು','digital':'ಡಿಜಿಟಲ್ ಪಾವತಿ','deliveryOtp':'ಡೆಲಿವರಿ OTP','generateOtp':'ಡೆಲಿವರಿ OTP ರಚಿಸಿ','confirmPickup':'ಪಿಕಪ್ ದೃಢೀಕರಿಸಿ','reachBuyer':'ಖರೀದಿದಾರರನ್ನು ತಲುಪಿದೆ','completeDelivery':'ಡೆಲಿವರಿ ಪೂರ್ಣಗೊಳಿಸಿ','receipt':'ರಸೀದಿ','bankDetails':'ರೈತ ಬ್ಯಾಂಕ್ ವಿವರಗಳು','accountHolder':'ಖಾತೆದಾರರ ಹೆಸರು','accountNumber':'ಬ್ಯಾಂಕ್ ಖಾತೆ ಸಂಖ್ಯೆ','ifsc':'IFSC ಕೋಡ್','bankName':'ಬ್ಯಾಂಕ್ ಹೆಸರು'}
};
